### ISSUE TITLE
<Trang> - Quản lý phòng ban

### ISSUE THREAD

**Issue by LongNguyen59** [QuanLyNhanSu-CNPMNC/QLNS#18]
* Thiết kế giao diện.
* Viết API.
* Gồm các chức năng:
- [x]  Thêm phòng ban
- [x] Có thể chọn một hoặc nhiều mục => Dùng để xóa một hoặc nhiều phòng ban.
- [x]  Sau khi chọn, có thể bỏ chọn tất cả mục được chọn hay bỏ chọn riêng lẻ từng mục
- [x] Sửa phòng ban
- [x] Hiển thị danh sách phòng ban
- [x]  Tìm kiếm phòng ban theo mã, tên phòng ban

**Comment by minhlan26** [comment]
![1](https://user-images.githubusercontent.com/74177482/119212629-d93e1880-bae3-11eb-8ccf-341f6f7656ec.png)
![2](https://user-images.githubusercontent.com/74177482/119212630-da6f4580-bae3-11eb-9c87-8fe21bfc60f2.png)
![3](https://user-images.githubusercontent.com/74177482/119212631-db07dc00-bae3-11eb-8892-7dd1d912a7ef.png)
![4](https://user-images.githubusercontent.com/74177482/119212634-dc390900-bae3-11eb-93a4-185ab486f809.png)
