### ISSUE TITLE
<Trang> - Quản lý chức vụ

### ISSUE THREAD

**Issue by LongNguyen59** [QuanLyNhanSu-CNPMNC/QLNS#21]
* Thiết kế giao diện.
* Viết API.
* Gồm các chức năng:
- [x]  Thêm chức vụ
- [x] Có thể chọn một hoặc nhiều mục => Dùng để xóa một hoặc nhiều chức vụ.
- [x]  Sau khi chọn, có thể bỏ chọn tất cả mục được chọn hay bỏ chọn riêng lẻ từng chức vụ
- [x] Sửa chức vụ
- [x] Hiển thị danh sách chức vụ
- [x]  Tìm kiếm phòng ban theo mã, tên chức vụ

**Comment by minhlan26** [comment]
![5](https://user-images.githubusercontent.com/74177482/119212930-d512fa80-bae5-11eb-8ae3-6e01418cf9c0.png)
![6](https://user-images.githubusercontent.com/74177482/119212931-d5ab9100-bae5-11eb-967b-ab4217fe946a.png)
![7](https://user-images.githubusercontent.com/74177482/119212932-d6442780-bae5-11eb-9628-4116759faf62.png)
![8](https://user-images.githubusercontent.com/74177482/119212934-d6dcbe00-bae5-11eb-919e-8469737ee7aa.png)

**Comment by minhlan26** [comment]
![1](https://user-images.githubusercontent.com/74177482/119228846-24d1e000-bb3f-11eb-809a-db5dc6feb2cf.png)
![2](https://user-images.githubusercontent.com/74177482/119228849-26030d00-bb3f-11eb-8c09-e17acf180040.png)
![3](https://user-images.githubusercontent.com/74177482/119228852-27343a00-bb3f-11eb-9ec5-0b6a859a430e.png)
![4](https://user-images.githubusercontent.com/74177482/119228854-28fdfd80-bb3f-11eb-8ca9-aaa432ecb5bb.png)
